version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: lenzingDB
    volumes:
      - ./mysql:/var/lib/mysql